"""
Webhook receive endpoints for platform integrations.

Each platform's webhook URL is auto-generated by MSuite App doctype.
Webhooks include ?ref={client_code} for multi-tenant routing.

Handles:
  - GET: Webhook verification (Meta hub.verify_token challenge)
  - POST: Event processing (signature validation, routing to client)

Actual event processing is deferred to future implementation.
This file establishes the routing skeleton.
"""
import hashlib
import hmac
import json

import frappe
from frappe import _
from frappe.utils.password import get_decrypted_password

from msuite.constants import MSUITE_LOGGER_NAME

logger = frappe.logger(MSUITE_LOGGER_NAME)


@frappe.whitelist(allow_guest=True)
def receive_meta_whatsapp(**kwargs):
    """
    WhatsApp Cloud API webhook endpoint.
    GET: Verification challenge from Meta.
    POST: Incoming messages, status updates, call events.
    """
    if frappe.request.method == "GET":
        return _handle_verification("Meta WhatsApp")

    # POST: validate signature and route
    if not _validate_meta_signature("Meta WhatsApp"):
        frappe.throw(_("Invalid webhook signature"), frappe.AuthenticationError)

    payload = frappe.request.get_json(silent=True) or {}

    # Extract WABA ID from payload to route to the correct client
    waba_id = ""
    try:
        waba_id = payload["entry"][0]["id"]
    except (KeyError, IndexError):
        pass

    # Forward payload to the client that owns this WABA
    if waba_id:
        _forward_to_client(waba_id, payload)

    return {"status": "ok"}


@frappe.whitelist(allow_guest=True)
def receive_meta_catalogue(**kwargs):
    """
    Meta Product Catalog webhook endpoint (`product_catalog` object).

    Named `receive_meta_catalogue` (not `..._catalog`) so it matches the URL
    `MSuite App._auto_generate_webhook_url` builds from the "Meta Catalogue"
    platform slug — same convention as receive_meta_whatsapp / _social.
    GET: Verification challenge from Meta.
    POST: `batch_status_updates` (async items_batch result) and
    `product_events` (Meta-initiated status change on an existing product).

    Routing is per-catalog: each `entry` carries a catalog_id, looked up via
    the `Meta Catalogue`-platform Connected Account (see meta_catalogue.py's
    discover_accounts) — same shape as the WABA-keyed WhatsApp routing below.
    """
    if frappe.request.method == "GET":
        return _handle_verification("Meta Catalogue")

    if not _validate_meta_signature("Meta Catalogue"):
        frappe.throw(_("Invalid webhook signature"), frappe.AuthenticationError)

    payload = frappe.request.get_json(silent=True) or {}
    object_type = payload.get("object", "product_catalog")

    for entry in payload.get("entry") or []:
        catalog_id = entry.get("id")
        if not catalog_id:
            continue
        # Rebuild a one-entry payload, same reason as `_dispatch_entry`
        # below: the shared Meta App receives every tenant's catalog
        # events in one webhook call, so each client only gets its own.
        forward_payload = {"object": object_type, "entry": [entry]}
        _forward_catalog_event(catalog_id, forward_payload)

    return {"status": "ok"}


def _forward_catalog_event(catalog_id: str, payload: dict) -> None:
    """Look up the Client that owns this Meta Product Catalog and forward
    the payload — catalog_id → MSuite Connected Account (Meta Catalogue) →
    MSuite Client."""
    connected = frappe.db.get_value(
        "MSuite Connected Account",
        {"account_id": catalog_id, "platform": "Meta Catalogue", "status": "Active"},
        ["client", "name"],
        as_dict=True,
    )
    if not connected:
        logger.debug(f"Catalog webhook for unknown catalog_id={catalog_id} — dropping")
        return

    client_doc = frappe.get_doc("MSuite Client", connected.client)
    if client_doc.status != "Active":
        logger.warning(
            f"Catalog webhook for catalog_id={catalog_id} → client {connected.client} "
            f"is {client_doc.status}, NOT forwarding"
        )
        return

    frappe.enqueue(
        "msuite.api.v1.webhook.forward_webhook_job",
        queue="short",
        client_name=client_doc.name,
        endpoint="msuite_workspace.meta_ecommerce.api.v1.webhook.receive_meta_catalog_event",
        payload=payload,
    )


@frappe.whitelist(allow_guest=True)
def receive_meta_social(**kwargs):
    """
    Meta Social webhook endpoint (Facebook / Instagram / Ads leadgen).
    GET: Verification challenge from Meta.
    POST: Leadgen events, feed/comment changes, etc.

    Routing is per-page: each `entry` carries a page_id; we group
    changes by page_id, look up the owning client via Connected
    Account, and forward the raw payload to that client's endpoint
    (ads.lead_events for leadgen; social.webhook for feed/comments
    once that lands).
    """
    if frappe.request.method == "GET":
        return _handle_verification("Meta Social")

    if not _validate_meta_signature("Meta Social"):
        frappe.throw(_("Invalid webhook signature"), frappe.AuthenticationError)

    payload = frappe.request.get_json(silent=True) or {}

    for entry in payload.get("entry") or []:
        page_id = entry.get("id")
        if not page_id:
            continue
        _dispatch_entry(page_id, entry, payload.get("object", "page"))

    return {"status": "ok"}


def _dispatch_entry(page_id: str, entry: dict, object_type: str) -> None:
    """Route one webhook entry to the owning client.

    We forward the whole original payload (wrapped around just this
    entry) so the client's handler sees a shape identical to what
    Meta sent — no custom re-wrapping to learn.

    Meta webhooks come in two shapes per entry:
      • entry[].changes[]    — feed/leadgen/comments (field-keyed)
      • entry[].messaging[]  — Instagram / Facebook DMs (Messenger-style)

    The DM shape doesn't carry a `field`; we route it as a unit to the
    client's Inbox DM endpoint. Comments / Feed continue through the
    field-map below.
    """
    if entry.get("messaging"):
        _dispatch_dm(page_id, entry, object_type)
        return

    for change in entry.get("changes") or []:
        field = change.get("field")
        endpoint = _endpoint_for_field(field)
        if not endpoint:
            logger.debug(f"No client endpoint for field={field}; skipping")
            continue

        # Rebuild a one-entry payload so the client side sees Meta's shape.
        forward_payload = {
            "object": object_type,
            "entry": [{"id": page_id, "time": entry.get("time"),
                       "changes": [change]}],
        }
        _forward_by_page(page_id, endpoint, forward_payload, object_type)


def _dispatch_dm(page_id: str, entry: dict, object_type: str) -> None:
    """Forward an Instagram / Facebook DM entry to the client's inbox.

    The platform-side id we received (`page_id` here) is either a Page
    id (object=page) or an IG Business Account id (object=instagram).
    Both resolve to a Social Account on the client side, so we use the
    same Facebook-platform Connected Account lookup the field-routing
    path uses — the platform is denormalised on the Connected Account.
    """
    platform = "Instagram" if object_type == "instagram" else "Facebook"
    connected = frappe.db.get_value(
        "MSuite Connected Account",
        {"account_id": page_id, "platform": platform, "status": "Active"},
        ["client", "name"],
        as_dict=True,
    )
    if not connected:
        logger.info(
            f"DM webhook for unknown {platform} id={page_id} — no active Connected Account."
        )
        return

    client_doc = frappe.get_doc("MSuite Client", connected.client)
    if client_doc.status != "Active":
        return

    forward_payload = {
        "object": object_type,
        "entry": [{"id": page_id, "time": entry.get("time"),
                   "messaging": entry.get("messaging") or []}],
    }
    frappe.enqueue(
        "msuite.api.v1.webhook.forward_webhook_job",
        queue="short",
        client_name=client_doc.name,
        endpoint="msuite_workspace.inbox.api.v1.webhook.receive_meta_dm",
        payload=forward_payload,
    )


# Per-field client endpoint map. Adding a new Meta webhook field is a
# one-line change here — the provider routes everything to the client
# by Page id; the client decides what to do with each field.
_FIELD_TO_ENDPOINT = {
    "leadgen":  "msuite_workspace.api.v1.ads.lead_events.receive_lead_event",
    # FB Page wall events (posts, comments, reactions). Provider relays
    # verbatim; client filters by `value.item` (comment / reaction / post).
    "feed":     "msuite_workspace.inbox.api.v1.webhook.receive_meta_feed",
    # IG comments on the connected Business/Creator account's media.
    "comments": "msuite_workspace.inbox.api.v1.webhook.receive_meta_ig_comments",
    # Meta Commerce order events (Shops/Instagram Shopping/Marketplace),
    # page/IG-scoped like leadgen/feed/comments above.
    "commerce_orders": "msuite_workspace.meta_ecommerce.api.v1.webhook.receive_meta_commerce_order",
}


def _endpoint_for_field(field: str) -> str | None:
    return _FIELD_TO_ENDPOINT.get(field)


def _forward_by_page(page_id: str, endpoint: str, payload: dict, object_type: str = "page") -> None:
    """Look up the Client that owns this Page/Instagram account and forward the payload.

    page_id → MSuite Connected Account (Facebook/Instagram) → MSuite Client.
    """
    platform = "Instagram" if object_type == "instagram" else "Facebook"
    connected = frappe.db.get_value(
        "MSuite Connected Account",
        {"account_id": page_id, "platform": platform, "status": "Active"},
        ["client", "name"],
        as_dict=True,
    )
    if not connected:
        logger.info(
            f"Webhook for unknown page_id={page_id} ({platform}) — no active Connected Account; skipping."
        )
        return

    client_doc = frappe.get_doc("MSuite Client", connected.client)
    if client_doc.status != "Active":
        logger.info(f"Client {connected.client} inactive; skipping forward.")
        return
    frappe.enqueue(
        "msuite.api.v1.webhook.forward_webhook_job",
        queue="short",
        client_name=client_doc.name,
        endpoint=endpoint,
        payload=payload,
    )


# ======================================================================
# Internal helpers
# ======================================================================


def _handle_verification(platform: str):
    """
    Handle Meta webhook verification challenge.
    Meta sends: GET ?hub.mode=subscribe&hub.verify_token=xxx&hub.challenge=yyy
    We return hub.challenge if verify_token matches our MSuite App config.
    """
    mode = frappe.form_dict.get("hub.mode", "")
    token = frappe.form_dict.get("hub.verify_token", "")
    challenge = frappe.form_dict.get("hub.challenge", "")

    if mode != "subscribe":
        frappe.throw(_("Invalid verification mode"), frappe.ValidationError)

    # Look up the expected verify token from MSuite App
    app_name = frappe.db.get_value(
        "MSuite App",
        {"platform": platform, "is_active": 1},
        "name",
    )
    if not app_name:
        frappe.throw(_("No active MSuite App for this platform"))

    expected_token = frappe.db.get_value(
        "MSuite App", app_name, "webhook_verify_token"
    )

    if not expected_token or token != expected_token:
        frappe.throw(_("Verify token mismatch"), frappe.AuthenticationError)

    # Meta expects the raw challenge number as plain text — not JSON wrapped.
    # Use Werkzeug Response directly to bypass Frappe's JSON serialization.
    from werkzeug.wrappers import Response
    frappe.response.http_status_code = 200
    return Response(str(challenge), content_type="text/plain")


@frappe.whitelist(allow_guest=True)
def deauthorize_callback(**kwargs):
    """
    Meta Deauthorize Callback — called when a user revokes app access
    via Facebook settings.

    Meta sends a POST with signed_request (base64url-encoded HMAC-SHA256).
    We decode it, extract the user_id, and mark matching accounts as Revoked.

    Returns a JSON with confirmation_code (Meta requires this).
    """
    import base64

    signed_request = frappe.form_dict.get("signed_request", "")
    if not signed_request:
        frappe.throw(_("Missing signed_request"), frappe.ValidationError)

    # signed_request format: "{signature}.{payload}" (base64url encoded)
    parts = signed_request.split(".", 1)
    if len(parts) != 2:
        frappe.throw(_("Invalid signed_request format"), frappe.ValidationError)

    encoded_sig, encoded_payload = parts

    # Try all active Meta apps to find the one that matches the signature
    apps = frappe.get_all(
        "MSuite App",
        filters={"platform": ["in", ["Meta WhatsApp", "Meta Social"]], "is_active": 1},
        fields=["name"],
    )

    validated = False
    payload_data = {}

    for app_rec in apps:
        app_secret = get_decrypted_password("MSuite App", app_rec.name, "app_secret")
        if not app_secret:
            continue

        # Validate HMAC-SHA256 signature
        expected_sig = hmac.new(
            app_secret.encode("utf-8"),
            encoded_payload.encode("utf-8"),
            hashlib.sha256,
        ).digest()

        # Decode the provided signature (base64url → bytes)
        # Add padding if needed
        padded_sig = encoded_sig + "=" * (4 - len(encoded_sig) % 4)
        try:
            decoded_sig = base64.urlsafe_b64decode(padded_sig)
        except Exception:
            continue

        if hmac.compare_digest(expected_sig, decoded_sig):
            # Decode the payload
            padded_payload = encoded_payload + "=" * (4 - len(encoded_payload) % 4)
            try:
                payload_data = json.loads(base64.urlsafe_b64decode(padded_payload))
            except Exception:
                continue
            validated = True
            break

    if not validated:
        frappe.throw(_("Signature validation failed"), frappe.AuthenticationError)

    user_id = payload_data.get("user_id", "")
    logger.info(f"Deauthorize callback received for Meta user_id: {user_id}")

    # Mark any Connected Accounts linked to this user as Revoked
    # user_id from Meta corresponds to the system user who authorized.
    # We search by the access_token being for this platform.
    # Since we can't directly map user_id → Connected Account, log for manual review.
    if user_id:
        frappe.log_error(
            title="Meta Deauthorize Callback",
            message=f"User {user_id} revoked app access. "
                    f"Review MSuite Connected Accounts for affected accounts.\n\n"
                    f"Payload: {json.dumps(payload_data)}",
        )

    # Meta requires a JSON response with a URL and confirmation code
    confirmation_code = frappe.generate_hash(length=10)
    return {
        "url": f"{frappe.utils.get_url()}/app/error-log",
        "confirmation_code": confirmation_code,
    }


def _forward_to_client(waba_id: str, payload: dict):
    """Forward a WhatsApp webhook payload to the client that owns this WABA."""
    connected = frappe.db.get_value(
        "MSuite Connected Account",
        {"account_id": waba_id, "platform": "WhatsApp", "status": "Active"},
        ["client", "name"],
        as_dict=True,
    )
    if not connected:
        # Shared Meta App receives webhooks for every WABA across all
        # tenants. Dropping unknown ones is correct routing. Debug-level
        # so other-tenant traffic doesn't spam the log.
        logger.debug(f"WhatsApp webhook for unknown WABA {waba_id} — dropping")
        return

    client_doc = frappe.get_doc("MSuite Client", connected.client)
    if client_doc.status != "Active":
        # Client is suspended / paused — surface as warning so support
        # can spot a stuck onboarding rather than a routing bug.
        logger.warning(
            f"WhatsApp webhook for WABA {waba_id} → client {connected.client} "
            f"is {client_doc.status}, NOT forwarding"
        )
        return

    frappe.enqueue(
        "msuite.api.v1.webhook.forward_webhook_job",
        queue="short",
        client_name=client_doc.name,
        endpoint="msuite_workspace.api.v1.whatsapp.webhook.webhook",
        payload=payload,
    )


def _post_to_client(client_doc, endpoint: str, payload: dict) -> None:
    """POST a payload to a client's whitelisted endpoint with provider auth.

    Shared forwarder used by every webhook path (WhatsApp, leadgen,
    future Social feed/comments). Auth is the inter-service
    X-MSuite-Provider-Key / -Secret pair that the client's
    `validate_provider_auth()` checks.
    """
    import requests
    from msuite.services.client_service import make_auth_headers

    url = f"{client_doc.client_url}/api/method/{endpoint}"
    try:
        resp = requests.post(
            url,
            headers=make_auth_headers(client_doc),
            json=payload,
            timeout=15,
        )
        if resp.status_code != 200:
            # Client returned non-200 — surface so client-side bugs are
            # diagnosable without enabling debug logs everywhere.
            logger.warning(
                f"Client forward to {endpoint} returned {resp.status_code} "
                f"({client_doc.name}): {resp.text[:200]}"
            )
        # Success path is intentionally silent — every healthy webhook
        # would otherwise write a log line and dwarf the signal we care
        # about (failures + drops).
    except Exception as e:
        logger.error(f"Failed to forward to {client_doc.name} {endpoint}: {e}")


def forward_webhook_job(client_name: str, endpoint: str, payload: dict) -> None:
    """Enqueued background job to forward a webhook payload to the client.

    By running this in the background, the webhook handler returns 200 OK
    immediately to Meta, preventing timeout retries.
    """
    client_doc = frappe.get_doc("MSuite Client", client_name)
    _post_to_client(client_doc, endpoint, payload)


def _validate_meta_signature(platform: str) -> bool:
    """
    Validate X-Hub-Signature-256 header against app secret.
    Meta signs webhook payloads with HMAC-SHA256 using the app secret.

    Returns:
        True if valid, False if invalid
    """
    signature_header = frappe.request.headers.get("X-Hub-Signature-256", "")
    if not signature_header:
        return False

    # Get app secret
    app_name = frappe.db.get_value(
        "MSuite App",
        {"platform": platform, "is_active": 1},
        "name",
    )
    if not app_name:
        return False

    app_secret = get_decrypted_password("MSuite App", app_name, "app_secret")
    if not app_secret:
        return False

    # Compute expected signature
    raw_body = frappe.request.get_data()
    expected = "sha256=" + hmac.new(
        app_secret.encode("utf-8"),
        raw_body,
        hashlib.sha256,
    ).hexdigest()

    match = hmac.compare_digest(expected, signature_header)
    if not match:
        frappe.log_error(
            title="Webhook Signature Mismatch",
            message=f"Platform: {platform}\n"
            f"Expected: {expected[:20]}...\n"
            f"Received: {signature_header[:20]}...\n"
            f"Body length: {len(raw_body)}\n"
            f"App: {app_name}",
        )
    return match


@frappe.whitelist(allow_guest=True)
def receive_gmail_push(**kwargs):
    """
    Google Pub/Sub push notification endpoint.
    GET: (Optional verification or basic request)
    POST: Real-time event containing base64 JSON payload.
    """
    if frappe.request.method == "GET":
        return {"status": "ok"}

    # Auth: Pub/Sub push carries a shared token in the endpoint URL query
    # string (?token=…), matched against `gmail_push_token` in site_config.
    # Fails closed — without it, anyone could POST fake pushes to trigger
    # sync jobs or probe which Gmail addresses are connected. The endpoint
    # only drives ingestion, so polling remains the fallback when unset.
    expected_token = frappe.conf.get("gmail_push_token")
    if not expected_token:
        logger.error("Gmail push received but gmail_push_token is not configured — rejecting.")
        frappe.throw(_("Gmail push authentication not configured"), frappe.AuthenticationError)
    # Read from the query string directly, not form_dict: Pub/Sub POSTs a
    # JSON body, and Frappe replaces form_dict with the parsed JSON — which
    # would drop the ?token=… query param.
    sent_token = (frappe.request.args.get("token") or "").strip()
    if not (sent_token and hmac.compare_digest(sent_token, str(expected_token))):
        frappe.throw(_("Invalid Gmail push token"), frappe.AuthenticationError)

    payload = frappe.request.get_json(silent=True) or {}
    message = payload.get("message", {})
    data_b64 = message.get("data")

    if not data_b64:
        logger.warning("Gmail push received but missing data key")
        return {"status": "ignored"}

    try:
        # Base64url decode Pub/Sub data
        import base64
        decoded_bytes = base64.urlsafe_b64decode(str(data_b64) + "===")
        data_json = json.loads(decoded_bytes.decode("utf-8"))
    except Exception as e:
        logger.error(f"Gmail push payload decode failed: {e}")
        return {"status": "error", "message": "Failed to decode base64 data"}

    email_address = data_json.get("emailAddress")
    history_id = data_json.get("historyId")

    if not email_address:
        logger.warning("Gmail push decoded data missing emailAddress")
        return {"status": "ignored"}

    # Find the active MSuite Connected Account matching this Gmail address
    connected = frappe.db.get_value(
        "MSuite Connected Account",
        {"account_id": email_address, "platform": "Gmail", "status": "Active"},
        ["client", "name"],
        as_dict=True,
    )
    if not connected:
        logger.info(f"Gmail push webhook for unknown email={email_address} — dropping")
        return {"status": "ignored"}

    client_doc = frappe.get_doc("MSuite Client", connected.client)
    if client_doc.status != "Active":
        return {"status": "ignored"}

    # Forward the incoming push event to the client's inbox ingestion endpoint
    frappe.enqueue(
        "msuite.api.v1.webhook.forward_webhook_job",
        queue="short",
        client_name=client_doc.name,
        endpoint="msuite_workspace.inbox.api.v1.email_ingest.receive_inbound_push",
        payload={
            "gmail_address": email_address,
            "history_id": history_id,
        },
    )

    return {"status": "ok"}

