class PlanTier:
    TRIAL = "Trial"
    BASIC = "Basic"
    PRO = "Pro"
    BUSINESS = "Business"
    ENTERPRISE = "Enterprise"
    ALL = [TRIAL, BASIC, PRO, BUSINESS, ENTERPRISE]


class GrantType:
    PAID = "Paid"
    COMPLIMENTARY = "Complimentary"
    BUNDLE = "Bundle"
    TRIAL = "Trial"
    ALL = [PAID, COMPLIMENTARY, BUNDLE, TRIAL]


class GrantStatus:
    ACTIVE = "Active"
    REVOKED = "Revoked"
    EXPIRED = "Expired"
    ALL = [ACTIVE, REVOKED, EXPIRED]


class FeatureType:
    BOOLEAN = "Boolean"
    NUMERIC = "Numeric"
    ENUM = "Enum"
    ALL = [BOOLEAN, NUMERIC, ENUM]


class SubscriptionStatus:
    DRAFT = "Draft"
    ACTIVE = "Active"
    CANCELLED = "Cancelled"
    COMPLETED = "Completed"


class PlanGrantType:
    COMPLIMENTARY = "Complimentary"


class CouponType:
    PROMOTIONAL = "Promotional"
    GIFT_CARD = "Gift Card"


class InvoiceStatus:
    DRAFT = "Draft"
    SUBMITTED = "Submitted"
    PAID = "Paid"
    UNPAID = "Unpaid"
    OVERDUE = "Overdue"
    CANCELLED = "Cancelled"


class ErrorCode:
    CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND"
    PLAN_NOT_FOUND = "PLAN_NOT_FOUND"
    SUBSCRIPTION_NOT_FOUND = "SUBSCRIPTION_NOT_FOUND"
    BUNDLE_NOT_FOUND = "BUNDLE_NOT_FOUND"
    INVOICE_NOT_FOUND = "INVOICE_NOT_FOUND"
    INVOICE_ALREADY_PAID = "INVOICE_ALREADY_PAID"
    DUPLICATE_PAYMENT_REQUEST = "DUPLICATE_PAYMENT_REQUEST"
    PAYMENT_VERIFICATION_FAILED = "PAYMENT_VERIFICATION_FAILED"
    DUPLICATE_PAYMENT = "DUPLICATE_PAYMENT"
    FEATURE_NOT_FOUND = "FEATURE_NOT_FOUND"
    INVALID_INPUT = "INVALID_INPUT"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    GRANT_ALREADY_EXISTS = "GRANT_ALREADY_EXISTS"
    TRIAL_PLAN_NOT_CONFIGURED = "TRIAL_PLAN_NOT_CONFIGURED"
    BUNDLE_MISCONFIGURED = "BUNDLE_MISCONFIGURED"
    AMENDMENT_FAILED = "AMENDMENT_FAILED"
    COUPON_NOT_FOUND = "COUPON_NOT_FOUND"
    COUPON_EXPIRED = "COUPON_EXPIRED"
    COUPON_MAX_USE_EXCEEDED = "COUPON_MAX_USE_EXCEEDED"
    COUPON_ALREADY_USED_BY_CUSTOMER = "COUPON_ALREADY_USED_BY_CUSTOMER"
    COUPON_INVALID = "COUPON_INVALID"
    CLIENT_NOT_FOUND = "CLIENT_NOT_FOUND"
    CLIENT_CONNECTION_FAILED = "CLIENT_CONNECTION_FAILED"
    CLIENT_ACTIVATION_FAILED = "CLIENT_ACTIVATION_FAILED"
    CLIENT_ALREADY_ACTIVE = "CLIENT_ALREADY_ACTIVE"


class ClientStatus:
    DRAFT = "Draft"
    ACTIVE = "Active"
    SUSPENDED = "Suspended"
    DISCONNECTED = "Disconnected"
    ALL = [DRAFT, ACTIVE, SUSPENDED, DISCONNECTED]


class SyncStatus:
    SUCCESS = "Success"
    FAILED = "Failed"


# Client sync thresholds
CLIENT_SYNC_MAX_FAILURES = 3
CLIENT_CONNECT_TIMEOUT = 10
CLIENT_PUSH_TIMEOUT = 15


MSUITE_CUSTOMER_GROUP_PREFIX = "MSuite"
MSUITE_PARENT_CUSTOMER_GROUP = "MSuite"
ENTITLEMENT_CACHE_TTL_SECONDS = 3600
ENTITLEMENT_CACHE_KEY_PREFIX = "msuite:entitlements"
TRIAL_PLAN_CACHE_KEY_PREFIX = "msuite:trial_plan"
TRIAL_PLAN_CACHE_TTL_SECONDS = 3600
MSUITE_LOGGER_NAME = "msuite"
TRIAL_DEFAULT_DAYS = 14
GRANT_RECONCILIATION_WINDOW_HOURS = 25
MSUITE_DISCOUNT_ACCOUNT = "Discounts - MSuite"

# Pricing Rule auto-creation for grant rules
MSUITE_PRICING_RULE_PREFIX = "MSuite"
PRICING_RULE_PRIORITY_COMPLIMENTARY = 10
PRICING_RULE_PRIORITY_DISCOUNT = 5


# ── Platform integration ──


class Platform:
    WHATSAPP = "WhatsApp"
    FACEBOOK = "Facebook"
    INSTAGRAM = "Instagram"
    META_ADS = "Meta Ads"
    GOOGLE = "Google"
    TIKTOK = "TikTok"
    LINKEDIN = "LinkedIn"
    TWITTER = "Twitter"
    ALL = [WHATSAPP, FACEBOOK, INSTAGRAM, META_ADS, GOOGLE, TIKTOK, LINKEDIN, TWITTER]


class ConnectedAccountStatus:
    ACTIVE = "Active"
    EXPIRED = "Expired"
    REVOKED = "Revoked"
    ALL = [ACTIVE, EXPIRED, REVOKED]


# Meta Graph API
GRAPH_API_VERSION = "v25.0"
GRAPH_API_BASE = f"https://graph.facebook.com/{GRAPH_API_VERSION}"

# OAuth
OAUTH_STATE_TTL_SECONDS = 600
OAUTH_STATE_CACHE_PREFIX = "msuite:oauth_state"

# Token refresh
TOKEN_REFRESH_BUFFER_DAYS = 7
